CREATE TABLE IF NOT EXISTS voters(
    voter_id INTEGER PRIMARY KEY NOT NULL,
    hash VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS polls(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    image VARCHAR(255) NOT NULL,
    begin_ts INTEGER NOT NULL,
    end_ts INTEGER NOT NULL,
    available_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS items_polls(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    poll_id INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS voters_polls(
    voter_id INTEGER NOT NULL,
    poll_id INTEGER NOT NULL,
    PRIMARY KEY(voter_id, poll_id)
);

CREATE TABLE IF NOT EXISTS tokens(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    voter_id INTEGER NOT NULL,
    token VARCHAR(255) NOT NULL,
    expiration_ts INTEGER NOT NULL
);
